name: 🟡 CD — Qualif

on:
  push:
    branches: [ "qualif" ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-docker.yml
    with:
      target: production
    secrets: inherit

  deploy:
    needs: build
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment-name: qualif
      compose-file: docker-compose.qualif.yml
      remote-path: /opt/apps/qualif
      health-url: https://qualif.your-app.com/health
      image-tag: ${{ needs.build.outputs.version }}
      enable-db-backup: true
    secrets: inherit