name: 🧪 CD — Test

on:
  push:
    branches: [ "devellop" ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-docker.yml
    with:
      target: production
    secrets: inherit

  deploy:
    needs: build
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment-name: test
      compose-file: docker-compose.test.yml
      remote-path: /opt/apps/test
      health-url: https://test.your-app.com/health
      image-tag: ${{ needs.build.outputs.version }}
      enable-db-backup: false
    secrets: inherit